<?php
	/*
	$DB_HOST = 'localhost:3306';
	$DB_USER = 'root';
	$DB_PASSWORD = 'password';
	$DB_NAME = 'SampleDB';
	//*/

	///*
	$DB_HOST = "{$MOPAAS_MYSQL10621_HOST}:{$MOPAAS_MYSQL10621_PORT}";
	$DB_USER = $MOPAAS_MYSQL10621_USER;
	$DB_PASSWORD = $MOPAAS_MYSQL10621_PASSWORD;
	$DB_NAME = $MOPAAS_MYSQL10621_NAME;
	//*/

	$DB_TABLE_NAME = 'SampleTable';
?>